### ISSUE TITLE
Empty iterator in MapPartition causes error

### ISSUE THREAD

**Issue by mcapuccini** [mcapuccini/EasyMapReduce#11]
```
java.lang.UnsupportedOperationException: empty.reduceLeft
	at scala.collection.TraversableOnce$class.reduceLeft(TraversableOnce.scala:180)
	at scala.collection.AbstractIterator.reduceLeft(Iterator.scala:1336)
	at scala.collection.TraversableOnce$class.reduce(TraversableOnce.scala:208)
	at scala.collection.AbstractIterator.reduce(Iterator.scala:1336)
	at se.uu.it.easymr.EasyMapReduce$$anonfun$2.apply(EasyMapReduce.scala:92)
	at se.uu.it.easymr.EasyMapReduce$$anonfun$2.apply(EasyMapReduce.scala:91)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$23.apply(RDD.scala:766)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:70)
	at org.apache.spark.scheduler.Task.run(Task.scala:85)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

https://github.com/mcapuccini/EasyMapReduce/blob/master/src/main/scala/se/uu/it/easymr/EasyMapReduce.scala#L92

**Comment by mcapuccini** [comment]
no longer a problem with new implementation
